# Rebuild the site daily at midnight pacific time
# Cron schedule is in UTC time: https://dateful.com/convert/utc
# Cron expression checker: https://crontab.cronhub.io/
name: "Cron-triggered rebuild"
on:
  schedule:
    - cron: '0 8 * * *'
jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: curl -X POST ${{ secrets.DEPLOY_HOOK }}
